---
title: "clean_IMPC_parameter_description"
output: html_document
date: "2024-12-23"
---


```{r}
library(dplyr)
library(ggplot2)
library(readr)
library(stringr)
```


```{r}
# Read the entire file content as a character vector, each line as an element
file_content <- readLines("/Users/joycedeng/Desktop/KCL_Bioinformatics/Data Cleaning and Data Management/project/Group2/IMPC_parameter_description.txt")

# Remove the first quoted section and any trailing quotes from each line
cleaned_content <- gsub('^"[^"]*"\\s+"|"$', "", file_content)

# Split the second line by commas and optional spaces to extract the header
header <- strsplit(cleaned_content[2], ",\\s*")[[1]]
data_lines <- cleaned_content[-1]

# Read the data lines into a data frame using the extracted header
parameter_description <- read.table(
  text = data_lines,
  sep = ",",
  col.names = header,
  stringsAsFactors = FALSE,
  quote = "\"",
  fill = TRUE,
  strip.white = TRUE
)

# Remove the first row if it contains duplicate header information
parameter_description <- parameter_description[-1, ]

# Reset row names to start from 1
rownames(parameter_description) <- NULL

dim(parameter_description)
# 5366   4
head(parameter_description)
```


```{r}
print(sum(duplicated(parameter_description$impcParameterOrigId)))
#26
print(sum(duplicated(parameter_description$name)))
#2807
print(sum(duplicated(parameter_description$description)))
#4146
print(sum(duplicated(parameter_description$parameterId)))
#1782
```

```{r}
# check the duplicate IDs

# Remove
parameter_description = parameter_description[!duplicated(parameter_description$impcParameterOrigId),]
# Check again
print(sum(duplicated(parameter_description$impcParameterOrigId)))

# Check valid parameterID with SOP
df_filtered <- parameter_description[nchar(parameter_description$parameterID) > 18, ]

print(df_filtered)
# All is valid

```

```{r}
duplicated_counts <- table(parameter_description$name[duplicated(parameter_description$name)])
print(duplicated_counts)

```

```{r}
# Check the dupliacte names
duplicate_name <- parameter_description %>% 
  dplyr::filter(duplicated(name),fromLast = TRUE) 

dim(duplicate_name)
```


```{r}
# Remove duplicate name
parameter_description <- parameter_description %>%
  group_by(name) %>%
  arrange(description, .by_group = TRUE) %>%
  slice(1) %>%  # Keep the first occurrence of each 'name' in the group
  ungroup()  

dim(parameter_description)
head(parameter_description)
```

```{r}
# Check the description
duplicate_description <- parameter_description %>% 
  dplyr::filter(duplicated(description),fromLast = TRUE) %>%
  select(impcParameterOrigId,name,description,parameterId)

duplicate_description

```







